### ISSUE TITLE
bug in your script "swap places with parent"

### ISSUE THREAD

**Issue by macmarrum** [macmarrum/freeplane-scripting#1]
Continued from https://github.com/freeplane/freeplane/discussions/693

@autoca wrote

> Hi macmarrum,
> 
> Your script "swap places with parent" seems to have a bug when trying to swap places with a parent that has a picture / image inserted. I got the feeling that such a picture may also affect other nodes in that branch to not work with your script anymore, but I could not establish a pattern for that extended effect.
> 
> At least, I could isolate it for the simple scenario: parent with pic -> child without pic. Please, see attached sample mindmap.
> 
> [test with pic.zip](https://github.com/freeplane/freeplane/files/9656243/test.with.pic.zip)
> 
> MTIA and regards, a.

**Comment by macmarrum** [comment]
It works for me on Linux.
Could you please attach logs?

**Comment by autoca** [comment]
I now realized that I forgot to pack the picture into the zip. Sorry. I am attaching it now.
However, which logs are you referring to?
![test](https://user-images.githubusercontent.com/37442404/192863105-dce18908-4b35-469b-9bd8-ee6670a5754b.png)

**Comment by macmarrum** [comment]
Close and reopen Freeplane.
In your test mindap, run the script to generate the error.
Go to `Tools->Open user directory` -> `logs`.
Attach `log.0`

The log file should contain information about the error.

**Comment by autoca** [comment]
Ok, thx, but I now saw that there is a lot of data in that log about which I don't understand whether it might contain too much private information. This is still a public space.

However, here is part of it, that seems like it might be relevant:
```
WARNING: error executing script C:\Users\....\AppData\Roaming\Freeplane\1.10.x\scripts\swapPlacesWithParent.groovy - giving up
java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Users\....\AppData\Local\Temp\freeplane\cachedImage11112473802818155896.image" "delete")
STDOUT: Sep 28, 2022 9:27:59 PM org.freeplane.core.util.LogUtils warn
WARNING: An error occured during the script execution: Freeplane groovy scripts are restricted. The following File operation is
    forbidden: Delete . You can change this in the program settings.
```
Well, I don't want to change that in the program settings. Dimitry in the preferences dialog specifically does not recommend doing so.

**Comment by macmarrum** [comment]
Yep. The reason for my script to fail is that Freeplane needs a delete permission to remove image cache when an image-node is moved.

The error can be isolated to the following instruction
```groovy
node.moveTo(node.parent.parent)
```

Please feel free to create a Freeplane bug: https://github.com/freeplane/freeplane/issues/new?created_from_discussion_number=693
